stages:
    - deploy
    - dev-push

deploy-dev:
  stage: dev-push
  only:
    - merge
  tags:
    - runner server
  script:
    - /home/gitlab-runner/shells/oikoscom/constructoratest.sh

deploy-prod:
    stage: deploy
    only:
        - production
    tags:
        - runner server
    script:
        - /home/gitlab-runner/shells/oikoscom/constructora.sh