stages:
    - deploy
    - test-push

deploy-test:
  stage: test-push
  only:
    - test
  tags:
    - runner server
  script:
    - /home/gitlab-runner/shells/oikoscom/constructoratest.sh

deploy-prod:
    stage: deploy
    only:
        - production
    tags:
        - runner server
    script:
        - /home/gitlab-runner/shells/oikoscom/constructora.sh